# Generated by Django 3.2.4 on 2021-06-17 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of project', max_length=100)),
                ('description', models.TextField(help_text='Description of project')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Date created')),
                ('updated_at', models.DateField(auto_now=True, help_text='Date updated')),
                ('duration', models.DurationField(help_text='Duration of Project')),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(help_text='Creator of the project', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
