# Generated by Django 3.2.4 on 2021-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of Project', null=True),
        ),
    ]
