# Generated by Django 3.2.4 on 2021-06-18 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(help_text='Deadline for task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(help_text='Start date for task', null=True),
        ),
    ]
