# Generated by Django 3.2.4 on 2021-06-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210618_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignee',
        ),
    ]
