# Generated by Django 3.2.4 on 2021-06-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='assigned_to',
            new_name='assignee',
        ),
    ]
